name: Maven Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      # Delete corrupted Maven repository
      - name: Force clean Maven repository
        run: rm -rf ~/.m2/repository

      # Ensure dependencies are redownloaded
      - name: Build with Maven (Force Update)
        run: mvn clean install -U -Dmaven.repo.local=~/.m2/repository -Dfile.encoding=UTF-8

      # Optional: Cache Maven dependencies (avoid using if issues persist)
      - name: Cache Maven Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}-${{ github.run_id }}
          restore-keys: |
            maven-
