name: Maven Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Clear Maven Cache
        run: rm -rf ~/.m2/repository

      - name: Build with Maven
        run: mvn clean install -U

      - name: Check Target Folder Contents
        run: ls -l target/
